### ISSUE TITLE
illegal syntax in syntax_to_i.Rd example

### ISSUE THREAD

**Issue by yrosseel** [sfcheung/semlbci#152]
In man/syntax_to_i.Rd line 88, an entry "not in table" is added to the pars vector. However, this line on its own is not valid lavaan syntax.  The current/old parser in lavaan does not trigger an error. Instead, the string "not in table" is simply added to the rhs of the previous syntax line, and so you get (after all spaces are removed): "ab:=2notintable", which is probably not what is intended.

The new parser (soon on github) will trigger an error, and flag this line as invalid syntax (that is how we found this issue). 

Is it possible to remove this "no in table" element in pars? Or you can make it a comment (adding '#' at the beginning).

**Comment by sfcheung** [comment]
@yrosseel , thanks for raising this issue. Users are not supposed to do the "not in table" things. I used this in the example just to show that invalid syntax will be ignored. If invalid syntax can be caught by the parser, it's a good thing. In any case, users are expected to write valid syntax.

I will fix this issue this weekend in the GitHub version and remove "no it table". If you need to submit a new version of lavaan to CRAN, let me know. I will submit a new version of semlbci to CRAN as soon as possible such that it won't affect your submission.

**Comment by yrosseel** [comment]
No hurry. The new lavaan parser seems to break many packages, so it will take a few weeks before everything is fixed.

**Comment by sfcheung** [comment]
Fixed in #153
